alter table if exists t_todo_detail drop constraint if exists FKllnxjlj4nsju17xyqxyycn3qq

drop table if exists demo cascade;
drop table if exists t_todo cascade;
drop table if exists t_todo_detail cascade;

create table demo (id int8 generated by default as identity, name varchar(255), primary key (id))
create table t_todo (id int8 generated by default as identity, created_at timestamp, updated_at timestamp, name varchar(255), sort_order int8, primary key (id))
create table t_todo_detail (id int8 generated by default as identity, created_at timestamp, updated_at timestamp, name varchar(255), sort_order int8, todo_id int8 not null, primary key (id))
alter table if exists t_todo_detail add constraint FKllnxjlj4nsju17xyqxyycn3qq foreign key (todo_id) references t_todo on delete cascade

INSERT INTO public.t_todo
(created_at, updated_at, "name", sort_order)
VALUES(current_date, current_date, 'Java', 1);
INSERT INTO public.t_todo
(created_at, updated_at, "name", sort_order)
VALUES(current_date, current_date, 'C#', 2);

INSERT INTO public.t_todo_detail
(created_at, updated_at, "name", sort_order, todo_id)
VALUES(current_date, current_date, 'Task 1', 1, 1);
INSERT INTO public.t_todo_detail
(created_at, updated_at, "name", sort_order, todo_id)
VALUES(current_date, current_date, 'Task 2', 2, 1);
INSERT INTO public.t_todo_detail
(created_at, updated_at, "name", sort_order, todo_id)
VALUES(current_date, current_date, 'Task 3', 3, 1);